/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.5-10.1.36-MariaDB : Database - todolist
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`todolist` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `todolist`;

/*Table structure for table `todo_tasks` */

DROP TABLE IF EXISTS `todo_tasks`;

CREATE TABLE `todo_tasks` (
  `TASK_ID` bigint(255) NOT NULL AUTO_INCREMENT,
  `TASK_TITLE` varchar(250) NOT NULL,
  `USER_ID` bigint(100) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`TASK_ID`),
  KEY `USER_ID_FK2` (`USER_ID`),
  CONSTRAINT `USER_ID_FK2` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=latin1;

/*Data for the table `todo_tasks` */

insert  into `todo_tasks`(`TASK_ID`,`TASK_TITLE`,`USER_ID`,`CREATED_DATE`) values (20,'dffdsf',1,'2018-11-11 19:48:37'),(24,'45454545',1,'2018-11-11 20:53:44'),(28,'tytyyrytry',1,'2018-11-11 22:58:04'),(29,'dfsfdsfsfs',1,'2018-11-11 22:58:07'),(32,'Task23223',1,'2018-11-11 22:58:30'),(33,'Task4546546',1,'2018-11-11 22:58:34');

/*Table structure for table `user_roles` */

DROP TABLE IF EXISTS `user_roles`;

CREATE TABLE `user_roles` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `USER_ROLE` varchar(30) NOT NULL,
  `STATUS` enum('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Data for the table `user_roles` */

insert  into `user_roles`(`ID`,`USER_ROLE`,`STATUS`,`CREATED_DATE`) values (1,'MASTER','ACTIVE','2018-11-11 14:10:12'),(2,'ADMIN','ACTIVE','2018-11-11 14:10:02');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `USER_ID` bigint(100) NOT NULL AUTO_INCREMENT,
  `USER_ROLE` int(10) NOT NULL,
  `USER_EMAIL` varchar(50) NOT NULL,
  `USER_PASSWORD` varchar(250) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  KEY `USER_ROLE_FOREIGN_KEY_ID` (`USER_ROLE`),
  CONSTRAINT `USER_ROLE_FOREIGN_KEY_ID` FOREIGN KEY (`USER_ROLE`) REFERENCES `user_roles` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `users` */

insert  into `users`(`USER_ID`,`USER_ROLE`,`USER_EMAIL`,`USER_PASSWORD`,`CREATED_DATE`) values (1,2,'ravi123@gmail.com','1790f19d6edb09a7a94870e99c7b0689','2018-11-11 14:15:18');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
